### ISSUE TITLE
training details

### ISSUE THREAD

**Issue by yingao123** [StefanFischer/MediastinalLymphNodeSegmentation#2]
I observe that you use many public datasets: lung tumors & full annotated lymph nodes & partial annotated abnormal lymph nodes. But your task is segmenting the abnormal lymph nodes in the mediastinal region. How did you use these datasets in your network training? Could you reveal some details? I am working on a similar task and trying to improve performance. 
  Hope for your response, very thanks to you!

**Comment by StefanFischer** [comment]
Hello Yingao,

yes i am using the additional datasets for training. The intention was to use them for semi-supervised training. From the datasets one can get the information that some of them also contain pathologic lymph nodes (Tumor staging: N-stage > 0). As the performance of my network most of the time decreased, when I integrated a semi-supervised learning technique, I dropped the semi-supervised learning later. I still had the additional data,  but one would need to verify if it is really helpful for the scenario without semi-supervised learning. I can still integrate the background voxels (those segmented by the Totalsegmentator tool) of the NSCLC  images as part of the training. The parts of the NSCLC images, that are not segmented by totalsegmentor and are not GT tumor voxels, will get ignored as they are set to the ignore class of nnUNet, such that they do not affect training. I am also thinking that the GT tumor annotations that come with the NSCLC dataset may are helpful, as they show some anomalies directly at the border to the mediastinum, that the network should not mistake for pathologic lymph nodes.

In total the use of those additional data was not validated to improve my results, they are only there cause of the original idea to integrate Pseudo Labeling/Entropy Minimization, which i got not to work stable on my task. So there might be additional class imbalance that i integrated to the training dataset.
